pekko {
  # Enable SLF4J logging backend
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"

  # Set internal threshold to DEBUG so logs reach Logback
  loglevel = "DEBUG"
  stdout-loglevel = "INFO"

  # Optional: Log complete HOCON configurations on ActorSystem initialization
  log-config-on-start = off

  http {
    server.preview.enable-http2 = on
  }
}


tcode-server{
  host = "127.0.0.1"
  host = ${?server.host}

  port = 57001
  port = ${?server.port}

  frontend-port = 3000
  frontend-port = ${?FRONTEND_PORT}

  allowed-origin = "http://localhost:"${tcode-server.frontend-port}
  allowed-origin = ${?CORS_ALLOWED_ORIGIN}

  base-dir = "/tmp"
  base-dir = ${?user.home}
  base-dir = ${?HOME}

  dict-dir = ${tcode-server.base-dir}"/.local/share/tcode-server/dictionary"

  databases {
    tcode-tbl = ${tcode-server.dict-dir}"/tcode_tbl.db"
    mazegaki  = ${tcode-server.dict-dir}"/mazegaki.db"
    bushu     = ${tcode-server.dict-dir}"/bushu.db"
  }
}