pekko.http.server.preview.enable-http2 = on

tcode-server{
  host = "127.0.0.1"
  host = ${?server.host}

  port = 57001
  port = ${?server.port}

  frontend-port = 3000
  frontend-port = ${?FRONTEND_PORT}

  allowed-origin = "http://localhost:"${tcode-server.frontend-port}
  allowed-origin = ${?CORS_ALLOWED_ORIGIN}

  base-dir = ${user.home}
  dict-dir = ${tcode-server.base-dir}"/.local/share/tcode-server/dictionary"
  dict-dir = ${?DICT_DIR}

  databases {
    tcode-tbl = ${tcode-server.dict-dir}"/tcode_tbl.db"
    mazegaki  = ${tcode-server.dict-dir}"/mazegaki.db"
    bushu     = ${tcode-server.dict-dir}"/bushu.db"
  }
}