package io.github.nicheapplab.tcodeserver

object EELLLTXT {
  case class LessonData(name: String, expected: Array[String], strokes: Array[String])

  val lessons = List(
    LessonData(
      "1 (RL)",
      Array("の、が、のが"),
      Array("kdjd;sjdkd;s")
    ),
    LessonData(
      "2 (RL)",
      Array("て、ての、と、のと、とか"),
      Array("lajdlakdjdjajdkdjajdjaje")
    ),
    LessonData(
      "3 (RL)",
      Array(
        "に、のに、にて、は、のは、ては",
        "で、ので、では、を、のを、とを"
      ),
      Array(
        "kgjdkdkgjdkglajdjgjdkdjgjdlajg",
        "hgjdkdhgjdhgjgjd;gjdkd;gjdja;g"
      )
    ),
    LessonData(
      "4 (RL)",
      Array(
        "た。たのが、でた。な、なので、なにを",
        "なのに、はでなたなをたてにたてた。"
      ),
      Array(
        "kshfkskd;sjdhgkshflgjdlgkdhgjdlgkg;g",
        "lgkdkgjdjghglgkslg;gkslakgkslakshf"
      )
    ),
    LessonData(
      "5 (RL)",
      Array(
        "なにをしないでいたいの。ない。はい。いないが",
        "なし。しては、をした。なる。でる。いたがると",
        "はるになると、たのしい。しているのがいるし"
      ),
      Array(
        "lgkg;gjslghdhghdkshdkdhflghdhfjghdhfhdlghd;s", // Insert T-Code strokes for lesson 5
        "lgjshfjslajgjd;gjskshflg;ahfhg;ahfhdks;s;aja",
        "jg;akglg;ajajdkskdjshdhfjslahd;akd;shd;ajs"
      )
    ),
    LessonData(
      "6 (RL)",
      Array(
        "(て)(に)(を)(は)",
        "して(しないで)、",
        "この、もの、どの、おのおの、",
        "おる。こる。たどる。ともる。"
      ),
      Array(
        "kelaidkekgidke;gidkejgid", // Insert T-Code strokes for lesson 6
        "jslakejslghdhgidjd",
        "ufkdjdiakdjdkqkdjdoakdoakdjd",
        "oa;ahfuf;ahfkskq;ahfjaia;ahf"
      )
    ),
    LessonData(
      "7 (RL)",
      Array(
        "どこにもおもいものはない。",
        "とらない。とる。とれ。",
        "とられた、これらの、",
        "どれもしらないので、",
        "これをとられてはいられない。"
      ),
      Array(
        "kqufkgiaoaiahdiakdjglghdhf",
        "jaiglghdhfja;ahfja;ehf",
        "jaig;eksjduf;eigkdjd",
        "kq;eiajsiglghdkdhgjd",
        "uf;e;gjaig;elajghdig;elghdhf"
      )
    ),
    LessonData(
      "8 (RL)",
      Array(
        "ある。いる。うる。える。おる。",
        "あおい、もう、たえなる、",
        "あれ、あなた、あるいは、あてる。",
        "こうした、とうとう、どうにも、おこなう。",
        "あなたのいえは、(どうしても)あれをこえるものにはならない。"
      ),
      Array(
        "yf;ahfhd;ahfyd;ahflt;ahfoa;ahf",
        "yfoahdjdiaydjdksltlg;ajd",
        "yf;ejdyflgksjdyf;ahdjgjdyfla;ahf",
        "ufydjsksjdjaydjaydjdkqydkgiajdoauflgydhf",
        "yflgkskdhdltjgjdkekqydjslaiaidyf;e;guflt;aiakdkgjglgiglghdhf"
      )
    ),
    LessonData(
      "9 (RL)",
      Array(
        "される。もっと、さらに、であろう。さて、",
        "うしろ、さっと、いろいろ、したがって、",
        "あさっては、はれるであろう。",
        "うろうろしていて、おろされた。",
        "から、きた、くる、こい、かった。",
        "しかし、とき、なくては、できる。",
        "かっこでくくることができる。",
        "きっとはがきをくれる。"
      ),
      Array(
        "ug;e;ahfiajrjajdugigkgjdhgyfpsydhfuglajd",
        "ydjspsjdugjrjajdhdpshdpsjdjsks;sjrlajd",
        "yfugjrlajgjdjg;e;ahgyfpsydhf",
        "ydpsydpsjslahdlajdoapsug;ekshf",
        "jeigjdhrksjdjt;ajdufhdjdjejrkshf",
        "jsjejsjdjahrjdlgjtlajgjdhghr;ahf",
        "jejrufhgjtjt;aufja;shghr;ahf",
        "hrjrjajg;shr;gjt;e;ahf"
      )
    ),
    LessonData(
      "10 (RL)",
      Array(
        "いないわ。いや、いるよ。",
        "わるい、よい、こわい、やさしい。",
        "おはよう、っていうのはいやよ。",
        "(わが)や(わたしの)がよい。",
        "なくさせる。あせらせる。",
        "しない。しよう。した。しろ。せよ。",
        "さようなら、おせわになって、どうも。",
        "にせものではないかしら。"
      ),
      Array(
        "hdlghdyshfhdyejdhd;ajwhf",
        "ys;ahdjdjwhdjdufyshdjdyeugjshdhf",
        "oajgjwydjdjrlahdydkdjghdyejwhf",
        "keys;sidyekeysksjskdid;sjwhdhf",
        "lgjtuguw;ahfyfuwiguw;ahf",
        "jslghdhfjsjwydhfjskshfjspshfuwjwhf",
        "ugjwydlgigjdoauwyskglgjrlajdkqydiahf",
        "kguwiakdhgjglghdjejsighf"
      )
    ),
    LessonData(
      "11 (RL)",
      Array(
        "やがて、もっとも、とうとう、たとえ、もし、やたらに、",
        "あるいは、どうか、たえて、さらさら、せっかく、",
        "おもしろかろう。よろしかったら、くどくて、えらい。せわしいとき、",
        "ややこしかろう。こわかった。うれしくて、さもしい。やさしいとき、",
        "あのようなものにせっせとかかわっていないで、",
        "かれらにしたがってよいことをしなさい。"
      ),
      Array(
        "ye;slajdiajrjaiajdjaydjaydjdksjaltjdiajsjdyeksigkgjd",
        "yf;ahdjgjdkqydjejdksltlajdugigugigjduwjrjejtjd",
        "oaiajspsjepsydhfjwpsjsjejrksigjdjtkqjtlajdltighdhfuwysjshdjahrjd",
        "yeyeufjsjepsydhfufysjejrkshfyd;ejsjtlajdugiajshdhfyeugjshdjahrjd",
        "yfkdjwydlgiakdkguwjruwjajejeysjrlahdlghdhgjd",
        "je;eigkgjsks;sjrlajwhdufja;gjslgughdhf"
      )
    ),
    LessonData(
      "12",
      Array(
        "「」「」「」「」「」",
        "「。」(「」、「、」、「。」)",
        "「あ」「か」「さ」「た」「な」",
        "「おはよう。」「さよなら。」",
        "そして、それは、その、ありそうな、",
        "おりおり、より、ありがとう。",
        "いそいそと、そこにいった。",
        "それよりかなりありそうな、",
        "きます。そうです。なにかする。",
        "まったく、まあ、そうすると、",
        "そのままかまわないで、",
        "すっかりすますまで、まってくれますか。"
      ),
      Array(
        ",gjv,gjv,gjv,gjv,gjv",
        ",ghfjvke,gjvjd,gjdjvjd,ghfjvid",
        ",gyfjv,gjejv,gugjv,gksjv,glgjv",
        ",goajgjwydhfjv,gugjwlgighfjv",
        ";bjslajd;b;ejgjd;bkdjdyfjc;bydlgjd",
        "oajcoajcjdjwjcjdyfjc;sjaydhf",
        "hd;bhd;bjajd;bufkghdjrkshf",
        ";b;ejwjcjelgjcyfjc;bydlgjd",
        "hrmd,fhf;bydhg,fhflgkgje,f;ahf",
        "mdjrksjtjdmdyfjd;byd,f;ajajd",
        ";bkdmdmdjemdyslghdhgjd",
        ",fjrjejc,fmd,fmdhgjdmdjrlajt;emd,fjehf"
      )
    ),
    LessonData(
      "13",
      Array(
        "もたない。もちます。もつ。もて。もとう。",
        "すなわち、つまり、ちっとも、ちりつつある。",
        "そのつどそちらにおうかがいいたします。",
        "ついでにわたしたちもおやつをもらいました。",
        "だ。です。ます。である。であります。",
        "だった。でした。ました。であった。でありました。",
        "「おれはそれだ」「わたしはこれです」",
        "「どちらさまがどれになさいますのですか」",
        "あちこちでこどもたちが、たいくつそうにしています。",
        "「いつ、もどりますか。」",
        "「そのうちもどるだろう。」"
     ),
      Array(
        "iakslghdhfia/amd,fhfia.dhfialahfiajaydhf",
        ",flgys/ajd.dmdjcjd/ajrjaiajd/ajc.d.dyf;ahf",
        ";bkd.dkq;b/aigkgoaydje;shdhdksjsmd,fhf",
        ".dhdhgkgysksjsks/aiaoaye.d;giaighdmdjskshf",
        "hchfhg,fhfmd,fhfhgyf;ahfhgyfjcmd,fhf",
        "hcjrkshfhgjskshfmdjskshfhgyfjrkshfhgyfjcmdjskshf",
        ",goa;ejg;b;ehcjv,gysksjsjguf;ehg,fjv",
        ",gkq/aigugmd;skq;ekglgughdmd,fkdhg,fjejv",
        "yf/auf/ahgufkqiaks/a;sjdkshdjt.d;bydkgjslahdmd,fhf",
        ",ghd.djdiakqjcmd,fjehfjv",
        ",g;bkdyd/aiakq;ahcpsydhfjv"
     ),
    ),
    LessonData(
      "14",
      Array(
        "めったに、みたいな、めそめそ、みちのく、",
        "ためしに、しめしめ、どろまみれ、",
        "こよみをめくる。ためるためのみに、",
        "きみみたいなめめしいやつとは、",
        "けっして、だんだん、そんな、だれ、だけを、",
        "けしからん。そうだけれども、けがしたんだ。",
        "やけにめんどうだけれど、",
        "ただただ、けしからんやつだ。",
        "みんなで「まとめだけではだめだ」といえますか。"
      ),
      Array(
        "lcjrkskgjd/gkshdlgjdlc;blc;bjd/g/akdjtjd",
        "kslcjskgjdjslcjslcjdkqpsmd/g;ejd",
        "ufjw/g;glcjt;ahfkslc;akslckd/gkgjd",
        "hr/g/gkshdlglclcjshdye.djajgjd",
        "nfjrjslajdhcndhcndjd;bndlgjdhc;ejdhcnf;gjd",
        "nfjsjeigndhf;bydhcnf;ekqiajdnf;sjsksndhchf",
        "yenfkglcndkqydhcnf;ekqjd",
        "kshckshcjdnfjsjeigndye.dhchf",
        "/gndlghg,gmdjalchcnfhgjghclchcjvjahdltmd,fjehf"
      )
    ),
    LessonData(
      "15",
      Array(
        "ばかり、ほとんど、じわじわ、ほほえみ、をば、",
        "ほおばる。じたばた、「ほら、しくじった。」",
        "ほどくのならば、まじめにほどいてほしい。",
        "じめじめすればするほど、じつにうっとうしい。",
        "まず、とげる。ずっと、もげる。",
        "うれしげに、よっつずつ、あげさげする。",
        "きずあとがずきずきとうずく。",
        "ずっとげらげらわらっていた。",
        "そればかりか、ずっとおよげずじまいだった。",
        "ほめられずくめ",
        "これにめげずに、しばしばいらしてください。"
      ),
      Array(
        ",wjejcjdpzjandkqjduxysuxysjdpzpzlt/gjd;g,wjd",
        "pzoa,w;ahfuxks,wksjd,gpzigjdjsjtuxjrkshfjv",
        "pzkqjtkdlgig,wjdmduxlckgpzkqhdlapzjshdhf",
        "uxlcuxlc,f;e,w,f;apzkqjdux.dkgydjrjaydjshdhf",
        "md,zjdja/z;ahf,zjrjajdia/z;ahf",
        "yd;ejs/zkgjdjwjr.d,z.djdyf/zug/z,f;ahf",
        "hr,zyfja;s,zhr,zhrjayd,zjthf",
        ",zjrja/zig/zigysigjrlahdkshf",
        ";b;e,wjejcjejd,zjrjaoajw/z,zuxmdhdhcjrkshf",
        "pzlcig;e,zjtlc",
        "uf;ekglc/z,zkgjdjs,wjs,whdigjslajthcughdhf"
      )
    ),
    LessonData(
      "16",
      Array(
        "012、210。",
        "10こ、2つ。",
        "2000人がたった1人になるまで",
        "10人から20人までにする。",
        "12345。5かける4は20。",
        "およそ、314くらいになる。",
        "はるは3月4月5月。15時は3時。"
      ),
      Array(
        "kf;d;fjd;f;dkfhf",
        ";dkfufjd;f.dhf",
        ";fkfkfkfma;sksjrks;dmakglg;amdhg",
        ";dkfmajeig;fkfmamdhgkg,f;ahf",
        ";d;fhaudldhfldjenf;audjg;fkfhf",
        "oajw;bjdha;dudjtighdkglg;ahf",
        "jg;ajghapfudpfldpfhf;dldmgjghamghf"
      )
    ),
    LessonData(
      "17",
      Array(
        "5678。7かけ8は56。",
        "7月から8月までなつやすみ。",
        "1868年7月7日",
        "あるいて6、7分",
        "99円にしないで、98円にする。",
        "1982-1997年のあいだに9人に1人になる。"
      ),
      Array(
        "ldifhekthfhejenfktjgldifhf",
        "hepfjeigktpfmdhglg.dye,f/ghf",
        ";dktifkt;thepfhekr",
        "yf;ahdlaifjdhehw",
        "kvkvkzkgjslghdhgjdkvktkzkg,f;ahf",
        ";dkvkt;fkc;dkvkvhe;tkdyfhdhckgkvmakg;dmakglg;ahf"
      )
    ),
    LessonData(
      "18",
      Array(
        "03(812)2111-4093",
        "113、7-3-1。920-09、4-8-605。",
        "1月1日、1月15日、2月11日、3月23日。",
        "4月29日、5月3日、5月5日、9月15日。",
        "9月23日、10月10日、11月3日、11月23日。",
        "645年、710年、794年、1192年。",
        "1604年、1868年、1945年、1982年。"
      ),
      Array(
        "kfhakekt;d;fid;f;d;d;dkcudkfkvha",
        ";d;dhajdhekchakc;dhfkv;fkfkckfkvjdudkcktkcifkfldhf",
        ";dpf;dkrjd;dpf;dldkrjd;fpf;d;dkrjdhapf;fhakrhf",
        "udpf;fkvkrjdldpfhakrjdldpfldkrjdkvpf;dldkrhf",
        "kvpf;fhakrjd;dkfpf;dkfkrjd;d;dpfhakrjd;d;dpf;fhakrhf",
        "ifudld;tjdhe;dkf;tjdhekvud;tjd;d;dkv;f;thf",
        ";difkfud;tjd;dktifkt;tjd;dkvudld;tjd;dkvkt;f;thf"
      )
    ),
    LessonData(
      "19",
      Array(
        "5時13分・6時18分・7時12分・8時9分、",
        "9時34分・10時56分・11時29分・12時54分、",
        "20時40分・21時25分・23時50分。",
        "2、3日もたてば、てんきもよくなるだろう。",
        "8時につくには、50分まえにはでていなければならない。",
        "1986年はとら年です。",
        "わたしも7月3日には24になります。"
      ),
      Array(
        "ldmg;dhahwlfifmg;dkthwlfhemg;d;fhwlfktmgkvhwjd",
        "kvmghaudhwlf;dkfmgldifhwlf;d;dmg;fkvhwlf;d;fmgldudhwjd",
        ";fkfmgudkfhwlf;f;dmg;fldhwlf;fhamgldkfhwhf",
        ";fjdhakriaksla,wjdlandhriajwjtlg;ahcpsydhf",
        "ktmgkg.djtkgjgjdldkfhwmdltkgjghglahdlgnf;e,wlgiglghdhf",
        ";dkvktif;tjgjaig;thg,fhf",
        "ysksjsiahepfhakrkgjg;fudkglgjcmd,fhf"
      )
    ),
    LessonData(
      "20",
      Array(
        "アレー、ルール、レール、",
        "レアー、ルアー、アール、",
        "レールのアレー、",
        "ルールではルアーをつかう。",
        "アート・ルート・レート、アルト、",
        "アース・レース・トースト、",
        "アート・ストアのストール",
        "ストのストレスをストレートに",
        "アトラス、トレーラー・ラリー、シー・スルー、",
        "リアルなスリラー、シールとレシート、",
        "リトル・ストリート、",
        "スリラー・ストーリーのシリアスなラスト。"
      ),
      Array(
        ";w;qhsjdkwhskwjd;qhskwjd",
        ";q;whsjdkw;whsjd;whskwjd",
        ";qhskwkd;w;qhsjd",
        "kwhskwhgjgkw;whs;g.djeydhf",
        ";whslelfkwhslelf;qhslejd;wkwlejd",
        ";whsualf;qhsualflehsualejd",
        ";whslelfuale;wkdualehskw",
        "ualekduale;qua;guale;qhslekg",
        ";wleusuajdle;qhsushslfuspdhsjdpghslfuakwhsjd",
        "pd;wkwlguapdushsjdpghskwja;qpghslejd",
        "pdlekwlfualepdhslejd",
        "uapdushslfualehspdhskdpgpd;wualgusualehf"
      )
    )
  )
}
